services:
    my-mongodb:
        image: mc-nest-product-db-image
        container_name: mc-nest-product-db-container
        ports:
            - 27017:27017
        volumes:
            - mongodb:${DATA_VOLUME}
            - mongoconfig:${CONFIG_VOLUME}
        networks:
            - mongo_net

volumes:
    mongodb:
    mongoconfig:

networks:
    mongo_net:
        driver: bridge
